[package]
name = "uniffi-dart"
version = "0.1.0"
edition = "2021"
license = "Apache-2 or MIT"
homepage = "https://github.com/acterglobal/uniffi-dart"
description = "Dart Frontend for UniFFI"

[features]
defaults = []
binary = ["dep:anyhow"]
build = [
    "dep:anyhow",
    "dep:uniffi_build",
]
bindgen-tests = [
    "dep:anyhow",
    "dep:uniffi_testing",
    "dep:heck",
    "dep:camino-tempfile",
    "dep:fs_extra",
    "dep:glob",
]

[lib]
name = "uniffi_dart"
path = "src/lib.rs"

[[bin]]
name = "uniffi_bindgen_dart"
path = "src/bin.rs"
required-features = ["binary"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uniffi = "0.23.0"
uniffi_bindgen = "0.23.0"
camino ="1"
serde = "1"
toml = "0.5"

# feature specific stuff
anyhow = { version = "1", optional = true}
uniffi_build = { version = "0.23.0", optional = true }

# optional for testint
uniffi_testing = { version = "0.23.0", optional = true }
fs_extra = { version = "1.3.0", optional = true }
heck = { version = "0.4.1", optional = true }
camino-tempfile = { version = "1.0.2", optional = true }
glob = { version = "0.3.1", optional = true}

[workspace]

members = [
    ".",

    # for testing
    "fixtures/*",
]